### ISSUE TITLE
Undefined index: variants on Print Docs

### ISSUE THREAD

**Issue by snetty** [damanic/ls1-module-shop#1]
doesn't appear to be any documentation on any changes that are required to support the new Order Docs feature, as a result printing invoices now fails even when Invoice Documentation Template is not set to Lemonstand Standard Docs (presumably the new variant option).

**Comment by damanic** [comment]
Thanks, fixed in latest release.

Look at `/modules/shop/invoice_templates/ls_variant/info.php` for example on how to create templates with variants.
