### ISSUE TITLE
Undefined property: Shop_TransactionUpdate::$created_at

### ISSUE THREAD

**Issue by patrickheeney** [damanic/ls1-module-shop#15]
I am unfamiliar with the changes in 869cbf9d476263898ed5ba6621437305b7a5fe77 but it seems to introduce a bug which caused our checkout process to fail.

```
 Phpr_PhpException: Undefined property: Shop_TransactionUpdate::$created_at. In /public_html/modules/shop/models/shop_paymenttransaction.php, line 88 
```

According to [Shop_TransactionUpdate](https://github.com/damanic/ls1-module-shop/blob/master/classes/shop_transactionupdate.php#L12) class, there is no `created_at` property. Also later in that [function](https://github.com/damanic/ls1-module-shop/blob/master/models/shop_paymenttransaction.php#L108) it checks for `isset` on `created_at`. From the comments it sounds like this is supposed to check for a duplicate using a property that doesn't exist. I don't have an understanding of what the original chnge was intended to solve so I am unsure of the best route to fix it.

**Comment by damanic** [comment]
You might want to consider setting your LS config files to ignore Phpr_PhpExceptions, and let your PHP.ini/system config handle PHP errors.

`$CONFIG['ERROR_IGNORE'] = array('Phpr_PhpException'); //excluded because it can occur before DB params initiated and subsequent attempts to log the error can crash the app`

---------

The created_at param was added to allow payment transaction updates to be logged with gateway datetime created instead of the time LS received the update.

I have pushed a commit to define the property and document.

**Comment by patrickheeney** [comment]
Would that help if you have `$CONFIG['ERROR_LOG'] = false;` and `$CONFIG['LOG_TO_DB'] = false;`? It still seems the error would crash the app. What else do you use for `$CONFIG['ERROR_REPORTING']`? Maybe you are disabling some other errors that are typically thrown?

In any case, I will give the latest updates a try. I am using Auth.net AIM which didn't seem to have a gateway datetime, thus triggering the error.

**Comment by damanic** [comment]
The issue raised here is valid but PHP error reporting can be logged outside of LS in PHP error log and not passed to LS for exception handling/logging.  PHP should not be halting the application with NOTICE / WARNING / DEPRECATED messages.

In this case the `Undefined property: ` is a NOTICE that should not have caused your checkout process to fail.

You can prevent this with PHP.ini error_reporting settings and setting LS config `ERROR_IGNORE` to ignore Phpr_PhpException

**Comment by patrickheeney** [comment]
Ah, I understand what you are saying now. I thought you were proposing ignoring the errors completely. In this case the error is on staging where the checkout was failing in order to catch any regressions like this one. The error reporting is quieter in production. I wish LS has an automated test suite, but that is another story.
