### ISSUE TITLE
Add property set to a product

### ISSUE THREAD

**Issue by putty2000** [damanic/ls1-module-shop#16]
when trying to add a property set to a product it flags this error:

`Error applying validation to existing_id column. Column type is unknown. Probably this is a calculated column. Please call the "type" method to set the column type.`

# | Call Stack Code | Document | Line
-- | -- | -- | --
12 | Db_ColumnDefinition->validation() | /modules/shop/models/shop_propertyset.php | 40
11 | Shop_PropertySet->define_form_fields() | /modules/shop/controllers/shop_products.php | 1670
10 | Shop_Products->onLoadPropertySetForm() | /phproad/modules/phpr/classes/phpr_controllerbase.php(250) : eval()'d code | 1
9 | eval() | /phproad/modules/phpr/classes/phpr_controllerbase.php | 250
8 | Phpr_ControllerBase->_execEventHandler() | /phproad/modules/phpr/classes/phpr_controller.php | 211
7 | Phpr_Controller->_execEventHandler() | /modules/backend/classes/backend_controller.php | 132
6 | Backend_Controller->_execEventHandler() | /phproad/modules/phpr/classes/phpr_controller.php | 140
5 | Phpr_Controller->dispatchEvents() | /phproad/modules/phpr/classes/phpr_controller.php | 84
4 | Phpr_Controller->_run() | /phproad/modules/phpr/classes/phpr_response.php | 55
3 | Phpr_Response->open() | /phproad/system/phproad.php | 31

**Comment by damanic** [comment]
I am not getting this error.

Please post version of shop module and steps to reproduce.

**Comment by damanic** [comment]
Found and fixed in commit b5486c2
