### ISSUE TITLE
Tier Price

### ISSUE THREAD

**Issue by putty2000** [damanic/ls1-module-shop#17]
Tier Price fields only works with a monetary value. Should this work with a % too, which would be a % off the base price or % off the sale price if the product is on sale?

**Comment by damanic** [comment]
@putty2000 
 Tier price and base price are price fields (money).
![image](https://github.com/user-attachments/assets/e804e2eb-b551-42b1-9906-c62e04bce9d4)

If you want to offer a percent discount for multiple units you can use the discount engine.
