### ISSUE TITLE
Call to a member function format_currency() 

### ISSUE THREAD

**Issue by rtddev** [damanic/ls1-module-shop#8]
@damanic - When creating/editing an order, if we try to use the "Edit Discount Manually" link on the Discounts tab, we're getting this error.

Fatal error: Call to a member function format_currency() on null in /home/xxxxxx/public_html/modules/shop/controllers/shop_orders/_order_discount_form.htm on line 12

![image](https://user-images.githubusercontent.com/1872898/55985061-c9d91980-5c53-11e9-8cc9-43705d3feda6.png)

I recall seeing currency-related updates recently and wondering if the above error is related.

**Comment by damanic** [comment]
@rtddev 
fixed in https://github.com/damanic/ls1-module-shop/commit/fd90d3b056215b8230d119f70706159e36fc9048

Will release shortly

**Comment by rtddev** [comment]
@damanic - thx!
